### ISSUE TITLE
size specifiers not highlighted

### ISSUE THREAD

**Issue by Starrlightz** [doinkythederp/nasm-language-support#13] opened 2022-10-15 11:00 UTC
byte, word, ... are not being highlighted 

```asm
mul byte [two]
mov al, byte[a]
```

**Comment by doinkythederp** [comment] 2022-10-15 18:58
Currently they're being marked as "operators" so I think this is just your theme. Would it make sense to you for them to be marked differently?
![Screen Shot 2022-10-15 at 11 58 09 AM](https://user-images.githubusercontent.com/75394401/196003555-c95cac06-4b64-412d-9712-eb4cd9ef175e.png)

**Comment by doinkythederp** [comment] 2022-10-22 23:50
@Starrlightz I'm going to close this soon since there hasn't been an update and this hasn't been confirmed as unexpected behavior.

**Closed** 2022-10-24 16:00 UTC
Labels: enhancement, tokenization, awaiting information
